-- CREAR SP CON PARAMETRO DE ENTRADA EL ANIO

	-- DECLARAR VARIABLES NECESARIAS
    -- DECLARAR CURSOR TRAYENDO LOS REGISTROS DE LAS MEDICIONES DEL ANIO PASADO POR PARAMETRO (CON LOS JOINS NECESARIOS), 
	-- AGRUPANDO POR USUARIO, DIA Y LOS DATOS QUE NECESITAMOS PARA INSERTAR, Y HACER UN PROMEDIO DE LOS VALORES MEDIDOS POR CADA DIA
	-- ALGO ASI (SELECT Usuario_idUsuario, DATE(m.timestamp), ROUND(AVG(m.valor)), + DATOS NECESARIOS
	--			 FROM medicion
	--			 JOINS NECESARIOS
	--			 WHERE YEAR(timestamp) = ANIO PARAMETRO
	--			 GROUP BY DE TODO LO QUE ESTA EN EL SELECT)
    
    -- DECLARAR HANDLER PARA SALIR DEL BUCLE DEL CURSOR
    -- DECLARAR HANDLER PARA CUALQUIER ERROR GENERICO
		-- CANCELAR LA TRANSACCION
		-- MOSTRAR ERROR CON UN SELECT
	
    -- ABRIR CURSOR
    -- ARRANCAR TRANSACCION
    
    -- DECLARAMOS BUCLE
		-- TRAER PROXIMO REGISTRO DEL CURSOR
        -- CONDICION DE SALIDA DEL BUCLE
        -- LLAMAMOS AL SP DEL PUNTO 1, SI NO EXISTE YA ESE REPORTE DIARIO (USAR LA FUNCION DEL PUNTO 2)
        
	-- CIERRA BUCLE
    -- CIERRA CURSOR
	
    -- CONFIRMAR TRANSACCION
    
-- TERMINA SP