-- MySQL Script generated by MySQL Workbench
-- lun 30 ago 2021 13:44:59 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify-equipo2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify-equipo2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify-equipo2` DEFAULT CHARACTER SET utf8 ;
USE `spotify-equipo2` ;

-- -----------------------------------------------------
-- Table `spotify-equipo2`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`artista` (
  `idArtista` INT NOT NULL,
  `nombreArtista` VARCHAR(45) NULL DEFAULT NULL,
  `imgArtista` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`pais` (
  `idpais` CHAR(5) NOT NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`discografica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`discografica` (
  `idDiscografica` INT NOT NULL,
  `nombreDiscografica` VARCHAR(45) NULL DEFAULT NULL,
  `pais_idpais` CHAR(5) NOT NULL,
  PRIMARY KEY (`idDiscografica`, `pais_idpais`),
  INDEX `fk_discografica_pais1_idx` (`pais_idpais` ASC) VISIBLE,
  CONSTRAINT `fk_discografica_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `spotify-equipo2`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`album` (
  `idAlbum` INT NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `publicacion` YEAR NULL DEFAULT NULL,
  `imgPortada` BLOB NULL DEFAULT NULL,
  `artista_idArtista` INT NOT NULL,
  `discografica_idDiscografica` INT NOT NULL,
  PRIMARY KEY (`idAlbum`, `artista_idArtista`, `discografica_idDiscografica`),
  INDEX `fk_album_artista1_idx` (`artista_idArtista` ASC) VISIBLE,
  INDEX `fk_album_discografica1_idx` (`discografica_idDiscografica` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idArtista`)
    REFERENCES `spotify-equipo2`.`artista` (`idArtista`),
  CONSTRAINT `fk_album_discografica1`
    FOREIGN KEY (`discografica_idDiscografica`)
    REFERENCES `spotify-equipo2`.`discografica` (`idDiscografica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`cancion` (
  `idCancion` INT NOT NULL,
  `tituloCancion` VARCHAR(45) NULL DEFAULT NULL,
  `duracionSeg` INT NULL DEFAULT NULL,
  `reproduccion` BIGINT NULL DEFAULT NULL,
  `like` BIGINT NULL DEFAULT NULL,
  `album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idCancion`, `album_idAlbum`),
  INDEX `fk_cancion_album1_idx` (`album_idAlbum` ASC) VISIBLE,
  CONSTRAINT `fk_cancion_album1`
    FOREIGN KEY (`album_idAlbum`)
    REFERENCES `spotify-equipo2`.`album` (`idAlbum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`genero` (
  `idgenero` INT NOT NULL,
  `autopercepcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`password` (
  `idPassword` INT NOT NULL,
  `vencimiento` DATETIME NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPassword`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`tipoUsuario` (
  `idtipoUsuario` INT NOT NULL,
  `tipoUsuario` VARCHAR(20) NULL,
  PRIMARY KEY (`idtipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`genero` (
  `idgenero` INT NOT NULL,
  `autopercepcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`usuario` (
  `idUsuario` INT NOT NULL,
  `mail` VARCHAR(100) NULL DEFAULT NULL,
  `fechaDeNacimiento` DATE NULL DEFAULT NULL,
  `codigoPostal` CHAR(5) NULL DEFAULT NULL,
  `password_idPassword` INT NOT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  `pais_idpais` CHAR(5) NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `password_idPassword`, `tipoUsuario_idtipoUsuario`, `pais_idpais`, `genero_idgenero`),
  INDEX `fk_usuario_password_idx` (`password_idPassword` ASC) VISIBLE,
  INDEX `fk_usuario_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC) VISIBLE,
  INDEX `fk_usuario_pais1_idx` (`pais_idpais` ASC) VISIBLE,
  INDEX `fk_usuario_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_password`
    FOREIGN KEY (`password_idPassword`)
    REFERENCES `spotify-equipo2`.`password` (`idPassword`),
  CONSTRAINT `fk_usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `spotify-equipo2`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `spotify-equipo2`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `spotify-equipo2`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`playlist` (
  `idPlaylist` INT NOT NULL,
  `tituloPlaylist` VARCHAR(30) NULL DEFAULT NULL,
  `cantidaCanciones` INT NULL DEFAULT NULL,
  `fechaCreacion` DATE NULL DEFAULT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`, `usuario_idUsuario`),
  INDEX `fk_playlist_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `spotify-equipo2`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`playlistActiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`playlistActiva` (
  `idPlaylistActiva` INT NOT NULL,
  `activa` TINYINT NULL DEFAULT NULL,
  `fechaBaja` DATE NULL DEFAULT NULL,
  `playlist_idPlaylist` INT NOT NULL,
  PRIMARY KEY (`idPlaylistActiva`, `playlist_idPlaylist`),
  INDEX `fk_playlistActiva_playlist1_idx` (`playlist_idPlaylist` ASC) VISIBLE,
  CONSTRAINT `fk_playlistActiva_playlist1`
    FOREIGN KEY (`playlist_idPlaylist`)
    REFERENCES `spotify-equipo2`.`playlist` (`idPlaylist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`playlistCancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`playlistCancion` (
  `idplaylistCancion` INT NOT NULL,
  `playlist_idPlaylist` INT NOT NULL,
  `cancion_idCancion` INT NOT NULL,
  PRIMARY KEY (`idplaylistCancion`, `playlist_idPlaylist`, `cancion_idCancion`),
  INDEX `fk_playlistCancion_playlist_idx` (`playlist_idPlaylist` ASC) VISIBLE,
  INDEX `fk_playlistCancion_cancion1_idx` (`cancion_idCancion` ASC) VISIBLE,
  CONSTRAINT `fk_playlistCancion_cancion1`
    FOREIGN KEY (`cancion_idCancion`)
    REFERENCES `spotify-equipo2`.`cancion` (`idCancion`),
  CONSTRAINT `fk_playlistCancion_playlist`
    FOREIGN KEY (`playlist_idPlaylist`)
    REFERENCES `spotify-equipo2`.`playlist` (`idPlaylist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`genero_has_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`genero_has_cancion` (
  `idgenero_has_cancion` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  `cancion_idCancion` INT NOT NULL,
  PRIMARY KEY (`idgenero_has_cancion`, `genero_idgenero`, `cancion_idCancion`),
  INDEX `fk_genero_has_cancion_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  INDEX `fk_genero_has_cancion_cancion1_idx` (`cancion_idCancion` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_cancion_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `spotify-equipo2`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_has_cancion_cancion1`
    FOREIGN KEY (`cancion_idCancion`)
    REFERENCES `spotify-equipo2`.`cancion` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
