-- MySQL Script generated by MySQL Workbench
-- sáb 28 ago 2021 13:49:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify-equipo2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify-equipo2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify-equipo2` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `spotify-equipo2` ;

-- -----------------------------------------------------
-- Table `spotify-equipo2`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`password` (
  `idPassword` INT NOT NULL,
  `vencimiento` DATETIME NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`idPassword`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`usuario` (
  `idUsuario` INT NOT NULL,
  `mail` VARCHAR(100) NULL,
  `fechaDeNacimiento` DATE NULL,
  `sexo` TINYINT NULL,
  `codigoPostal` CHAR(5) NULL,
  `pais` VARCHAR(100) NULL,
  `password_idPassword` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `password_idPassword`),
  INDEX `fk_usuario_password_idx` (`password_idPassword` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_password`
    FOREIGN KEY (`password_idPassword`)
    REFERENCES `spotify-equipo2`.`password` (`idPassword`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`playlist` (
  `idPlaylist` INT NOT NULL,
  `tituloPlaylist` VARCHAR(30) NULL,
  `cantidaCanciones` INT NULL,
  `fechaCreacion` DATE NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`, `usuario_idUsuario`),
  INDEX `fk_playlist_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `spotify-equipo2`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`artista` (
  `idArtista` INT NOT NULL,
  `nombreArtista` VARCHAR(45) NULL,
  `imgArtista` BLOB NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`discografica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`discografica` (
  `idDiscografica` INT NOT NULL,
  `nombreDiscografica` VARCHAR(45) NULL,
  `paisDiscografica` VARCHAR(45) NULL,
  PRIMARY KEY (`idDiscografica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`album` (
  `idAlbum` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `publicacion` YEAR NULL,
  `imgPortada` BLOB NULL,
  `artista_idArtista` INT NOT NULL,
  `discografica_idDiscografica` INT NOT NULL,
  PRIMARY KEY (`idAlbum`, `artista_idArtista`, `discografica_idDiscografica`),
  INDEX `fk_album_artista1_idx` (`artista_idArtista` ASC) VISIBLE,
  INDEX `fk_album_discografica1_idx` (`discografica_idDiscografica` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idArtista`)
    REFERENCES `spotify-equipo2`.`artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_discografica1`
    FOREIGN KEY (`discografica_idDiscografica`)
    REFERENCES `spotify-equipo2`.`discografica` (`idDiscografica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`cancion` (
  `idCancion` INT NOT NULL,
  `tituloCancion` VARCHAR(45) NULL,
  `duracionSeg` INT NULL,
  `reproduccion` BIGINT NULL,
  `like` BIGINT NULL,
  `album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idCancion`, `album_idAlbum`),
  INDEX `fk_cancion_album1_idx` (`album_idAlbum` ASC) VISIBLE,
  CONSTRAINT `fk_cancion_album1`
    FOREIGN KEY (`album_idAlbum`)
    REFERENCES `spotify-equipo2`.`album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`playlistActiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`playlistActiva` (
  `idPlaylistActiva` INT NOT NULL,
  `activa` TINYINT NULL,
  `fechaBaja` DATE NULL,
  `playlist_idPlaylist` INT NOT NULL,
  PRIMARY KEY (`idPlaylistActiva`, `playlist_idPlaylist`),
  INDEX `fk_playlistActiva_playlist1_idx` (`playlist_idPlaylist` ASC) VISIBLE,
  CONSTRAINT `fk_playlistActiva_playlist1`
    FOREIGN KEY (`playlist_idPlaylist`)
    REFERENCES `spotify-equipo2`.`playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify-equipo2`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-equipo2`.`genero` (
  `idgenero` INT NOT NULL,
  `nombreGenero` VARCHAR(45) NULL,
  `cancion_idCancion` INT NOT NULL,
  PRIMARY KEY (`idgenero`, `cancion_idCancion`),
  INDEX `fk_genero_cancion1_idx` (`cancion_idCancion` ASC) VISIBLE,
  CONSTRAINT `fk_genero_cancion1`
    FOREIGN KEY (`cancion_idCancion`)
    REFERENCES `spotify-equipo2`.`cancion` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`playlistCancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`playlistCancion` (
  `idplaylistCancion` INT NOT NULL,
  `playlist_idPlaylist` INT NOT NULL,
  `cancion_idCancion` INT NOT NULL,
  PRIMARY KEY (`idplaylistCancion`, `playlist_idPlaylist`, `cancion_idCancion`),
  INDEX `fk_playlistCancion_playlist_idx` (`playlist_idPlaylist` ASC) VISIBLE,
  INDEX `fk_playlistCancion_cancion1_idx` (`cancion_idCancion` ASC) VISIBLE,
  CONSTRAINT `fk_playlistCancion_playlist`
    FOREIGN KEY (`playlist_idPlaylist`)
    REFERENCES `spotify-equipo2`.`playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlistCancion_cancion1`
    FOREIGN KEY (`cancion_idCancion`)
    REFERENCES `spotify-equipo2`.`cancion` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
