-- MySQL Script generated by MySQL Workbench
-- sáb 28 ago 2021 12:50:13 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema UniversoLector
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UniversoLector
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniversoLector` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `UniversoLector` ;

-- -----------------------------------------------------
-- Table `UniversoLector`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Autor` (
  `codigo` INT NOT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Editorial` (
  `codigo` INT NOT NULL,
  `razon_social` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Libro` (
  `codigo` INT NOT NULL,
  `isbn` VARCHAR(13) NULL DEFAULT NULL,
  `titulo` VARCHAR(200) NULL DEFAULT NULL,
  `anio_escritura` YEAR NULL DEFAULT NULL,
  `anio_edicion` YEAR NULL DEFAULT NULL,
  `codigo_autor` INT NULL DEFAULT NULL,
  `codigo_editorial` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_autor` (`codigo_autor` ASC) VISIBLE,
  INDEX `codigo_editorial` (`codigo_editorial` ASC) VISIBLE,
  CONSTRAINT `Libro_ibfk_1`
    FOREIGN KEY (`codigo_autor`)
    REFERENCES `UniversoLector`.`Autor` (`codigo`),
  CONSTRAINT `Libro_ibfk_2`
    FOREIGN KEY (`codigo_editorial`)
    REFERENCES `UniversoLector`.`Editorial` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Socio` (
  `codigo` INT NOT NULL,
  `dni` VARCHAR(100) NULL DEFAULT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `localidad` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Prestamo` (
  `codigo` INT NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `fecha_devolucion` DATE NULL DEFAULT NULL,
  `fecha_tope` DATE NULL DEFAULT NULL,
  `codigo_socio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_socio` (`codigo_socio` ASC) VISIBLE,
  CONSTRAINT `Prestamo_ibfk_1`
    FOREIGN KEY (`codigo_socio`)
    REFERENCES `UniversoLector`.`Socio` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`Volumen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`Volumen` (
  `codigo` INT NOT NULL,
  `deteriorado` TINYINT(1) NULL DEFAULT NULL,
  `codigo_libro` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_libro` (`codigo_libro` ASC) VISIBLE,
  CONSTRAINT `Volumen_ibfk_1`
    FOREIGN KEY (`codigo_libro`)
    REFERENCES `UniversoLector`.`Libro` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`PrestamoxVolumen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`PrestamoxVolumen` (
  `codigo` INT NOT NULL,
  `codigo_prestamo` INT NOT NULL,
  `codigo_volumen` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_prestamo` (`codigo_prestamo` ASC) VISIBLE,
  INDEX `codigo_volumen` (`codigo_volumen` ASC) VISIBLE,
  CONSTRAINT `PrestamoxVolumen_ibfk_1`
    FOREIGN KEY (`codigo_prestamo`)
    REFERENCES `UniversoLector`.`Prestamo` (`codigo`),
  CONSTRAINT `PrestamoxVolumen_ibfk_2`
    FOREIGN KEY (`codigo_volumen`)
    REFERENCES `UniversoLector`.`Volumen` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UniversoLector`.`TelefonoxSocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversoLector`.`TelefonoxSocio` (
  `codigo` INT NOT NULL,
  `nro_telefono` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_socio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_socio` (`codigo_socio` ASC) VISIBLE,
  CONSTRAINT `TelefonoxSocio_ibfk_1`
    FOREIGN KEY (`codigo_socio`)
    REFERENCES `UniversoLector`.`Socio` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
